
import guis.ContactEditorUI;
import guis.NewRoutin;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Suporte
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    
    public MenuPrincipal() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        mainJPImg = new componentes.UJPanelImagem();
        jbIni = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbVisu = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RoutinBackUp");
        setBackground(new java.awt.Color(0, 102, 102));
        setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        setForeground(java.awt.Color.blue);

        mainJPImg.setImagem(new java.io.File("C:\\Users\\Suporte\\Desktop\\Desenvolvimento\\imagens\\fundo.png"));

        jbIni.setBackground(new java.awt.Color(0, 153, 153));
        jbIni.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbIni.setForeground(new java.awt.Color(240, 240, 240));
        jbIni.setText("Início");
        jbIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniActionPerformed(evt);
            }
        });

        jbNovo.setBackground(new java.awt.Color(0, 153, 153));
        jbNovo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbNovo.setForeground(new java.awt.Color(240, 240, 240));
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbVisu.setBackground(new java.awt.Color(0, 153, 153));
        jbVisu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbVisu.setForeground(new java.awt.Color(240, 240, 240));
        jbVisu.setText("Visualizar");

        jbExit.setBackground(new java.awt.Color(0, 153, 153));
        jbExit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbExit.setForeground(new java.awt.Color(240, 240, 240));
        jbExit.setText("Sair");

        mainPanel.setFocusable(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout mainJPImgLayout = new javax.swing.GroupLayout(mainJPImg);
        mainJPImg.setLayout(mainJPImgLayout);
        mainJPImgLayout.setHorizontalGroup(
            mainJPImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPImgLayout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(jbIni, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jbVisu)
                .addGap(28, 28, 28)
                .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        mainJPImgLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbExit, jbIni, jbNovo, jbVisu});

        mainJPImgLayout.setVerticalGroup(
            mainJPImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPImgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(mainJPImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbIni)
                    .addGroup(mainJPImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbNovo)
                        .addComponent(jbVisu)
                        .addComponent(jbExit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jbIniActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        // TODO add your handling code here:
        NewRoutin newrout = new NewRoutin();
        mainPanel.remove(this);
        this.mainPanel.add(newrout);
        this.pack();
        //mainPanel.setBackground(Color.red);
        
        
    }//GEN-LAST:event_jbNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbIni;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbVisu;
    private componentes.UJPanelImagem mainJPImg;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MenuPrincipal().setVisible(true);
                }
            });
        }
}
